# Generated by Django 5.1.2 on 2025-03-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpf_sensor_service', '0006_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorconfig',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sensormeasurement',
            name='measuredAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
