# Generated by Django 5.1.2 on 2025-09-03 08:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpf_sensor_service', '0007_sensorconfig_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorconfig',
            name='sensorType',
            field=models.CharField(default='sensor', max_length=24),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measuredAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='images/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fpf_sensor_service.sensorconfig')),
            ],
        ),
    ]
