# Generated by Django 5.1.2 on 2025-09-20 09:24

import django.db.models.deletion
import fpf_sensor_service.models.action
import fpf_sensor_service.models.hardware
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpf_sensor_service', '0008_sensorconfig_sensortype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('actionClassId', models.UUIDField()),
                ('isActive', models.BooleanField(default=False)),
                ('isAutomated', models.BooleanField(default=False)),
                ('maximumDurationSeconds', models.IntegerField(default=0)),
                ('additionalInformation', models.TextField(blank=True)),
                ('orderIndex', models.IntegerField(default=fpf_sensor_service.models.action.get_order_index_default)),
            ],
            options={
                'ordering': ['orderIndex'],
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('orderIndex', models.IntegerField(default=fpf_sensor_service.models.hardware.get_order_index_default)),
            ],
            options={
                'ordering': ['orderIndex'],
            },
        ),
        migrations.CreateModel(
            name='ActionTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('actionValueType', models.CharField(max_length=64)),
                ('actionValue', models.CharField(max_length=128)),
                ('triggerLogic', models.TextField()),
                ('description', models.TextField(null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='fpf_sensor_service.action')),
            ],
        ),
        migrations.CreateModel(
            name='ActionQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('startedAt', models.DateTimeField(null=True)),
                ('endedAt', models.DateTimeField(null=True)),
                ('value', models.TextField(null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queueEntries', to='fpf_sensor_service.action')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpf_sensor_service.actiontrigger')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='fpf_sensor_service.hardware'),
        ),
    ]
