# Generated by Django 5.1.2 on 2025-11-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpf_sensor_service', '0009_action_hardware_actiontrigger_actionqueue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='pingEndpoint',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sensorconfig',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fpf_sensor_service.hardware'),
        ),
    ]
