# Generated by Django 5.1.2 on 2025-12-04 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpf_sensor_service', '0010_hardware_pingendpoint_sensorconfig_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='nextAction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fpf_sensor_service.action'),
        ),
    ]
