# Generated by Django 5.1.2 on 2025-12-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpf_sensor_service', '0011_action_nextaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionqueue',
            name='dependsOn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fpf_sensor_service.actionqueue'),
        ),
    ]
